### ISSUE TITLE
Do we still need Default=False?

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#412] opened 2019-10-12 02:14 UTC
After doing several tests with and without Default=False, there seems to be no difference with it being in entries or not with CCleaner. BleachBit has a tool that just removes this value and Tron and System Ninja seems to just ignore this value anyways.

Is there any reason we still keep this? If not, then I think we can just remove it from Winapp2.

**Comment by APMichael** [comment] 2019-10-12 10:06
I think that "Default" is used because we follow the official syntax. Since then nobody has experimented with it. (The removal only makes sense if we have an updated Winap2ool.)

**Comment by ROCKNROLLKID** [comment] 2019-10-12 22:03
Let's see what @MoscaDotTo has to say. I mean we did also stop using specialdetect from the official syntax, too, so I don't think it's that big of a deal.

Have you tested this out yourself, yet?

**Comment by ROCKNROLLKID** [comment] 2019-10-12 22:14
@ShaneGowland @az0 @vocatus

I suppose we should get your guys opinions on this, too, since this may effect your programs. Can you guys confirm you do not use Default=False and that if we do remove it, it will not effect your programs?

**Comment by ShaneGowland** [comment] 2019-10-12 23:57
System Ninja just ignores it. Instead, the entries with "Warning=" in them are marked as non-default and require opt-in.

**Comment by az0** [comment] 2019-10-13 00:56
To save space, I delete the whole line before distributing the file. If it were included, it would be ignored anyway.

**Comment by APMichael** [comment] 2019-10-13 09:34
> Have you tested this out yourself, yet?

Yes, I can confirm that CCleaner obviously does not need the line "Default=False". And it's ok if they are removed. (I just meant that we should wait until a Winapp2ool with disabled WinappDebug scanning options 7+22 is available. Otherwise, WinappDebug will report thousands of errors.)

**Comment by MoscaDotTo** [comment] 2019-10-13 14:19
I will alter winapp2ool to only alert if it detects a Default=True rather than the absence of Default=False

**Comment by MoscaDotTo** [comment] 2019-10-13 22:06
winapp2ool now only informs a user if it detects a default value and, if repairing defaults, simply removes it

**Comment by ROCKNROLLKID** [comment] 2019-10-13 23:33
When you roll the next Winapp2ool update out, we can remove Default=False out then.

**Comment by APMichael** [comment] 2019-10-16 09:49
> When you roll the next Winapp2ool update out, we can remove Default=False out then.

Should we wait for a stable release or should we remove the "Default" lines now and ask users to use the beta version of Winapp2ool?

**Comment by ROCKNROLLKID** [comment] 2019-10-16 16:34
Next stable. I'd rather not force beta versions on people.

**Comment by MoscaDotTo** [comment] 2020-04-21 23:31
winapp2ool now enforces that there be no default specified

**Closed by MoscaDotTo** 2020-04-21 23:31 UTC
Labels: discussion, question

**Comment by APMichael** [comment] 2020-04-22 09:12
Ok, I will wait with the change until the new version is officially available under "Releases".

https://github.com/MoscaDotTo/Winapp2/releases
