### ISSUE TITLE
Winapp2ool silent command line switches

### ISSUE THREAD

**Issue by ricktendo** [MoscaDotTo/Winapp2#200] opened 2018-02-14 17:10 UTC
Would it be possible to add unattended silent switches to Winapp2ool for downloading, trim, path, etc.?

Example:
winapp2ool.exe /download /ini /directory:.\example_dir
winapp2ool.exe /download /exe /directory:.\example_dir
winapp2ool.exe /trim /default
winapp2ool.exe /trim /custom /parent
winapp2ool.exe /trim /custom /directory:.\example_dir

Thanks

**Comment by MoscaDotTo** [comment] 2018-03-18 04:59
I have tackled the bulk of this work in https://github.com/MoscaDotTo/Winapp2/commit/cae340ae8389e2a5cd715ea61a77cd04c0572b97

It's not fool proof yet, though it does try to discard bad parameterizations. I rewrote portions of most of the modules to better structure the code that initializes them to allow for this (ie. most modules now all some sort of initalization function that validates its parameters before beginning the main task). 

There's a good chance that there's still a wide variety of unexpected behaviors waiting to be discovered through use of this system, however here's the current workings:

Global flag: -s
the -s flag will silence the program, stopping it from giving any output. This will automatically ignore errors and confirm file overwrites.

One underdeveloped and untested aspect of this is giving an invalid path to a file via the command line, doing so will probably result in the ini file validator prompt appearing but not printing its output, making the program appear to be broken. 

WinappDebug:
default parameters:
directory: current directory
filename: winapp2.ini
autocorrect: off

flags:
-c : toggles the autocorrect feature on 

-d "some_file_path" : You can feed this either a full file path or a sub folder of the current directory by prefixing the parameterization with \ (eg "\winapp2ool downloads\winapp2.ini"). This will let you specify a full file path with directory for the directory and filename parameters. This is true of any call for any -*d call

-f "some_file_name" : If your file is in the current directory, you can target it by specifying just the name with this flag. If you for some reason specify both a -*d and *f, the -*f will overwrite the filename from the -*d. This is true for any -*f call.

Trim:
Default parameters:
winappDir, saveDir:  Current directory 
winappName, saveName: winapp2.ini
download: false
downloadncc: false 

flags:

-d : downloads the latest winapp2.ini from github to trim

-ncc : downloads the latest non-ccleaner winapp2.ini from github to trim

-wd "some_file_path" : specify the full path for winapp2.ini (see above for details)
-wf "some_file_name: : specify just the filename for winapp2.ini (see above for details)
-sd "some_file_path" : specify the full path for the save file
-sf "some_file_name" : specify just the file name for the save file

Merge:
Default parameters:
Mergemode: true (Replace & Add)
winappDir = secondFileDir = Current Directory
winappName = winapp2.ini
secondFileName = ""

flags: 

-mm : sets the mergemode to Remove & Add

-r : specifies the second file name to be removed entries.ini

-c : specifies the second file name to be custom.ini 

-fd "some_file_path" : full path to first file
-sd "some_file_path" : full path to second file
-ff "some_file_name: : just first file name
-sf "some_file_name: : just second file name

Diff:
Default parameters: 
ncc: false
download: false
firstDir = secondDir: current directory
first filename: winapp2.ini
second filename: ""
save: false

flags: 

-d : downloads the latest winapp2.ini for the diff

-ncc : downloads the latest non-ccleaner winapp2.ini for the diff

-l : toggles on saving of diff.txt to the current directory 

-fd "some_file_path" : full path to first file
-sd "some_file_path" : full path to second file
-ff "some_file_name: : just first file name
-sf "some_file_name: : just second file name

CCiniDebug:
default parameters:
winappdir = ccleanerinidir = current directory
winappname: winapp2.ini
ccleanerininame: ccleaner.ini
prune: false

flags:

-p : toggles on pruning using winapp2.ini (off by default)

-wd "some_file_path" : specify the full path for winapp2.ini 
-wf "some_file_name" : specify just the name for winapp2.ini
-cd "some_file_path" : specify the full path for ccleaner.ini
-cf "some_file_name" : specify just the name for ccleaner.ini

Download:
default parameters: 
download dir: current directory\winapp2ool downloads
downloadname: ""
downloadFile: 

flags:

-p : switches the download directory to the current directory 

(One caveat here is that the numerical flags right now as I've written the program must be the first flag you feed after the menu flag, or must immediately follow the -p flag)

1: download winapp2.ini
2: download non-ccleaner winapp2.ini
3: download winapp2ool.exe
4: download removed entries.ini 

-dd "some_file_path" : specify the full save path
-df "some_file_name: : specify just the save file name 



That's pretty much the gist of it right now. If you find any weird behavior, report it here.

**Comment by MoscaDotTo** [comment] 2018-03-18 05:07
Sorry, important tidbit I forgot to mention: The first flag you hand winapp2ool.exe should be the menu number of the tool you want to run. 

so winappdebug: 1
trim: 2
merge: 3
diff: 4
ccinidebug: 5
download: 6

So if you wanted to silently download winapp2.ini to the current directory, the call would look like 

winapp2ool.exe 6 1 -s -p

**Comment by MoscaDotTo** [comment] 2018-05-31 23:58
Just to update on this since #245 has changed a lot since I last commented on this

The syntax for commandline operations has been changed in 0.85b 

Right now, I haven't audited the commandline handler against all of the changes I've made internally to modules recently, so I can't guarantee that it will totally work under all circumstances, but I've tested some remote calls using the UI that use the same underlying mechanisms to launch the modules as does the commandline and the results have been good so far.

Commandline now starts out with 3 inifile objects, these will hold and paths or filenames you decide to input 

The way this works is generally as follows:

\#d - Takes a full path including filename and uses this as your target file for the respective file object by number 

\#f - Takes just a file name or subdirectory of the current directory with file name and assigns it to the filename portion of the respective file object by number

There are 3 such files, so proper commands for this look like 
`-1d "C:\Program Files\Winapp2ool\winapp2.ini" `
`-2f "\winapp2ool downloads\winapp2.ini"`
`-3f "winapp2.ini"`

and so forth. Each module handles handles these objects (firstFile, secondFile, thirdFile) in different ways, sometimes ignoring them all together depending on which configuration you select for the module. This will be elaborated on per module below

#WinappDebug:  
```
File Usage: 

firstFile: Your local copy of winapp2.ini
* default: ..\winapp2.ini 

secondFile: The save destination for when auto correct is enabled 
* default: ..\winapp2.ini 

Flags:

-c       : enable autocorrect 
* default: disabled 
```

#Trim: 
```
File Usage: 

firstFile:  Your local copy of winapp2.ini
* default:  ..\winapp2.ini

secondFile: The save destination for the trimmed file
* default:  ..\winapp2.ini

Flags:

-d       :  Download the latest ccleaner winapp2.ini
* default: disabled

-ncc     : Download the latest non-ccleaner winapp2.ini (implies -d) 
* default: disabled
```

#Merge: 
```
File Usage:

firstFile: Your local copy of winapp2.ini
* default: ..\winapp2.ini

secondFile: The file you want to merge with winapp2.ini
* default: Empty (module will not run without setting a value for this first) 

thirdFile: The save destination for the merged file
* default: ..\winapp2.ini

Flags:

-mm      : Toggle merge mode to replace & remove
* default: Replace & Add 

-r       : Use 'removed entries.ini' as the secondFile name 

-c       : Use 'custom.ini' as the secondFile name 
```

#Diff: 
```
File Usage:

firstFile: Your local copy of winapp2.ini
* default: ..\winapp2.ini

secondFile: The file against which you wish to diff your local copy of winapp2.ini
* default: empty (module will not run unless a value is set for this) 

thirdFile: The save location for Diff's output 
* default: ..\diff.txt

Flags:

-d       : Download and use the latest version of winapp2.ini from GitHub as the secondFile
* default: off

-ncc     : Download and use the latest version of the non-ccleaner winapp2.ini as the secondFile 
* default: off 

-savelog : enable saving the Diff log
* default: off 
```

#CCiniDebug:
```
File Usage: 

firstFile: Your local copy of winapp2.ini
* default: ..\winapp2.ini

secondFile: Your local copy of ccleaner.ini
*  default: ..\ccleaner.ini

thirdFile: The save destination for the modified ccleaner.ini 
* default: ..\ccleaner.ini

Flags: 

-noprune : Disable pruning of stale winapp2.ini entries
* default: enabled 

-nosort  : Disable alphabetical sorting of ccleaner.ini 
* default: enabled

-nosave  : Disable saving the modified ccleaner.ini
* default: enabled
```

#Downloader:
File Usage: Download directory is always the current directory, this will likely be changed to follow the proper format above in a later release

Flags:

1     : download winapp2.ini
2     : download non-ccleaner winapp2.ini
3     : download winapp2ool.exe
4     : download removed entries.ini
```

Additionally, calling -s should suppress any output the tool would give allowing it to run silently. Feel free to give it a try in 0.85beta or newer and report back if you notice broken things

**Comment by ricktendo** [comment] 2018-06-21 01:43
Can you give us examples of how to download and trim winapp2.ini, my previous command lines no longer work

`winapp2ool.exe 2 -d -s`

**Comment by MoscaDotTo** [comment] 2018-06-21 15:15
It appears this is broken right now (as I didn't test commandline stuff before pushing 0.85 

Instead you can use 2 calls for now

winapp2ool.exe 6 1 -s
winapp2ool.exe 2 -s 

Saving this as a bat would work until I have time to work on this

**Comment by MoscaDotTo** [comment] 2018-12-17 22:53
Work for this is done for winapp2ool 1.0 and documentation for using it can be found in the readme for winapp2ool so I am closing this. Any further, more specific issues with the commandline handling can be filed anew. \o/

**Closed by MoscaDotTo** 2018-12-17 22:53 UTC
Labels: enhancement
