### ISSUE TITLE
Deletes desktop icon settings

### ISSUE THREAD

**Issue by bee43** [MoscaDotTo/Winapp2#289] opened 2018-06-30 03:34 UTC
I've been using winapp2.ini for Ccleaner for a while. When using versions of winapp2.ini higher than 171113, Ccleaner deletes my desktop icon settings. Icons set to large go back to medium, and the way they're arranged goes back to default. It's definitely newer versions of winapp2.ini (higher than 171113) where the problem occurs. When I remove the newer one and revert to 171113 (or lower) the problem disappears. I didn't change any Ccleaner settings, just updated winapp2.ini and nothing else. Any ideas?

**Comment by APMichael** [comment] 2018-06-30 08:49
I guess it's caused by the entry "Windows ShellBags".

(But with version 180102 the Desktop issue should be fixed.)

**Comment by bee43** [comment] 2018-07-02 04:18
Thanks for writing. Indeed, unclicking "Windows Shellbags" makes the issue go away, so clearly the problem is there. Just one thing. The latest winapp2.ini I have is 180627. You just said 180102. Numerically that seems to be a lower version. Please clarify.

**Comment by APMichael** [comment] 2018-07-02 08:44
Yes, version 180102 is older (version number = year month day). I meant that the community added a fix for the Desktop issue in version 180102. This fix is also included in the latest version 180627. But I found out, that the fix doesn't work as expected. Therefore, you should use the latest version 180627 and unclick "Windows ShellBags".

**Comment by APMichael** [comment] 2018-07-03 11:47
I found the culprit: To protect the Desktop settings, we also have to exclude the value "NodeSlot" under the key "HKCU\\Software\\Microsoft\\Windows\\Shell\\BagMRU". Unfortunately, an ExcludeKey for the Registry supports only whole keys and no single values. Therefore, a fix isn’t possible.

An alternative could be splitting the entry into 2 entries, because since Windows Vista the main location for ShellBags is the key "HKCU\\Software\\Classes\\Local Settings\\Software\\Microsoft\\Windows\\Shell". For example:

[Windows ShellBags 1 \*]
LangSecRef=3025
Detect=HKCU\\Software\\Microsoft\\Windows
Default=False
Warning=This will reset folders and desktops size, view, icon or position settings to default and remove traces of the folders that do not exist anymore.
RegKey1=HKCU\\Software\\Microsoft\\Windows\\Shell\\BagMRU
RegKey2=HKCU\\Software\\Microsoft\\Windows\\Shell\\Bags
RegKey3=HKCU\\Software\\Microsoft\\Windows\\ShellNoRoam\\BagMRU
RegKey4=HKCU\\Software\\Microsoft\\Windows\\ShellNoRoam\\Bags
ExcludeKey1=REG|HKCU\\Software\\Microsoft\\Windows\\Shell\\Bags\\1\\Desktop
ExcludeKey2=REG|HKCU\\Software\\Microsoft\\Windows\\Shell\\Bags\\AllFolders
ExcludeKey3=REG|HKCU\\Software\\Microsoft\\Windows\\ShellNoRoam\\Bags\\1\\Desktop
ExcludeKey4=REG|HKCU\\Software\\Microsoft\\Windows\\ShellNoRoam\\Bags\\AllFolders

[Windows ShellBags 2 \*]
DetectOS=6.0|
LangSecRef=3025
Detect=HKCU\\Software\\Microsoft\\Windows
Default=False
Warning=This will reset folders size, view, icon or position settings to default and remove traces of the folders that do not exist anymore.
RegKey1=HKCU\\Software\\Classes\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\BagMRU
RegKey2=HKCU\\Software\\Classes\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\Bags
ExcludeKey1=REG|HKCU\\Software\\Classes\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\Bags\\AllFolders

@ROCKNROLLKID and @MoscaDotTo: What's your opinion? Ideas for better entry names? Or should we leave the present entry as is?

**Comment by ROCKNROLLKID** [comment] 2018-07-03 19:50
I think it would be better to just not use that entry if you use a custom desktop. This entry is not friendly to manual adjustments.

**Comment by CSGalloway** [comment] 2018-07-03 21:58
If [Windows ShellBags 2 *] has a DetectOS, wouldn't it make sense for [Windows ShellBags 1 *] to also have one? Sicne it doesn't - doesn't it mean that on some systems you might get both 1 and 2 to appear?

**Comment by APMichael** [comment] 2018-07-04 09:28
@CSGalloway: [Windows ShellBags 1 \*] doesn't need a DetectOS, because the Registry keys are used in all Windows version (from XP to 10). The Registry keys of [Windows ShellBags 2 \*] aren't used in Windows XP, because they exist only since Windows Vista. It was intended that both entries appear on Windows Vista to 10. If you have changed the Desktop settings you can only use [Windows ShellBags 2 \*], if not you can use both.

@ROCKNROLLKID: Ok, then we let the present entry as is.

**Comment by CSGalloway** [comment] 2018-07-04 16:52
@APMichael I use Windows 7 and get both Shellbags. There is not a warning on shellbags 2 to only use that one if you have changed the desktop settings.... and one similarly on 1 for that matter...

**Comment by APMichael** [comment] 2018-07-04 17:32
@CSGalloway: I had changed the warning on [Windows ShellBags 1 \*] to "This will reset folders **and desktops**...". But the two entries were just suggestions. They are not in the current Winapp2.ini and they probably won't be added in the future.

**Closed** 2018-07-09 08:15 UTC
