### ISSUE TITLE
[BleachBit] Tampermonkey loses all scripts.

### ISSUE THREAD

**Issue by Dra9o** [MoscaDotTo/Winapp2#728] opened 2020-08-09 01:44 UTC
Due

`[Edge Download History *]
LangSecRef=3006
DetectFile=%LocalAppData%\Microsoft\Edge*
FileKey1=%LocalAppData%\Microsoft\Edge*\User Data\*|*.ldb;*.log;CURRENT;LOCK;MANIFEST-*`

Is it REALY download history? I mean log - is a log file. CURRENT - looks like cache. And so on.

Key file to me is
`\AppData\Local\Microsoft\Edge\User Data\Default\Local Extension Settings\iikmkjmpaadaobahmlepeloendndfphd\000003.log`
It's definitely Tampermonkey error - who stores scripts and settings in log files. But anywar - Edge Download History looks wierd.

**Comment by APMichael** [comment] 2020-08-09 09:21
The .log files in Chromium-based browsers and applications are not usual log files, but very important parts of databases.

The FileKey deletes all files belonging to a database, so that a new empty database can be created at the next start.

All information about this database (LevelDB): https://github.com/google/leveldb/blob/master/doc/impl.md

I don't know of any Winapp2.ini entry that would clean the folder "Local Extension Setting", so you have to find out which CCleaner entry deletes the scripts of Tampermonkey.

**Comment by APMichael** [comment] 2020-08-09 09:59
I installed Tampermonkey under Edge Chromium as a test and then cleaned up with all CCleaner entries (the default entries as well as the entries from Winapp2.ini and Winapp3.ini). None of these entries delete the scripts.

The only way to delete the scripts is to delete the files in the "Local Extension Setting" folder. But there is no entry for this, as already written. Did you possibly make a custom entry for it?

**Comment by Dra9o** [comment] 2020-08-09 23:55
Thank you for fast reply.

I did not create custom entries.

I am using Edge 84.0.522.52 and BleachBit 4.0.0

Here are some sections that can delete those files:
```
[Edge Logs *]
LangSecRef=3006
DetectFile=%LocalAppData%\Microsoft\Edge*
FileKey1=%LocalAppData%\Microsoft\Edge*\Application|debug.log
FileKey2=%LocalAppData%\Microsoft\Edge*\User Data\*|LOG;LOG.old|RECURSE
FileKey3=%ProgramFiles%\Microsoft\Edge*\Application|debug.log
```
```
[Edge Download History *]
LangSecRef=3006
DetectFile=%LocalAppData%\Microsoft\Edge*
FileKey1=%LocalAppData%\Microsoft\Edge*\User Data\*|*.ldb;*.log;CURRENT;LOCK;MANIFEST-*
```

I suggest adding this:
```
ExcludeKey1=PATH|%LocalAppData%\Microsoft\Edge*\User Data\*Extension*\|*3.log
```

**Comment by Dra9o** [comment] 2020-08-09 23:56
To filter out lines like
`...\Edge\User Data\Default\Local Extension Settings\abdoipkehojnmbecdolgkolfenlegbfb\000003.log`

**Comment by APMichael** [comment] 2020-08-10 08:18
I have now checked it with BleachBit 4.0.0 and was able to reproduce the problem. However, the problem is not caused by the Winapp2.ini, but by a dangerous bug in BleachBit: BleachBit seems to put a wildcard before each search pattern!

Example:
FileKey2=%LocalAppData%\Microsoft\Edge\User Data\Default|LOG;LOG.old|RECURSE

This FileKey should only delete files that are named exactly "LOG" or "LOG.old". BleachBit deletes however "*LOG" and "*LOG.old":
```
Delete 0 C:\Users\xxx\AppData\Local\Microsoft\Edge\User Data\Default\Local Extension Settings\iikmkjmpaadaobahmlepeloendndfphd\BleachBit.log
Delete 0 C:\Users\xxx\AppData\Local\Microsoft\Edge\User Data\Default\Local Extension Settings\iikmkjmpaadaobahmlepeloendndfphd\BleachBitlog
Delete 0 C:\Users\xxx\AppData\Local\Microsoft\Edge\User Data\Default\Local Extension Settings\iikmkjmpaadaobahmlepeloendndfphd\BleachBit.log.old
Delete 0 C:\Users\xxx\AppData\Local\Microsoft\Edge\User Data\Default\Local Extension Settings\iikmkjmpaadaobahmlepeloendndfphd\BleachBitlog.old
```
This is a very dangerous behavior for a cleanup tool and definitely a bug!

Please report this bug directly to BleachBit: https://github.com/bleachbit/bleachbit/issues

**Comment by Dra9o** [comment] 2020-08-10 17:41
Thank you.

Just one moment:  BleachBit by default update Winapp2.ini at every startup. Are you shure that there was no recovered *.log file mask?

**Comment by APMichael** [comment] 2020-08-10 18:51
Yes, I know that BleachBit updates the Winapp2.ini with every new start and this must be blocked before.

But in this case it doesn't matter, because the involved entry [Edge Logs \*] doesn't contain a search pattern with "\*.log". 

(The other entry [Edge Download History \*] has nothing to do with the problem.)

**Comment by Dra9o** [comment] 2020-08-11 16:28
```
[Edge Download History *]
%LocalAppData%\Microsoft\Edge*\User Data\*|*.log
```
=> 

`C:\Users\xxx\AppData\Local\Microsoft\Edge\User Data\Default\Local Extension Settings\iikmkjmpaadaobahmlepeloendndfphd\BleachBit.log`

Isn't it?

**Comment by APMichael** [comment] 2020-08-11 16:48
No, please read what I wrote in my last post:

> (The other entry [Edge Download History \*] has nothing to do with the problem.)

The entry [Edge Download History \*] has no "RECURSE" command.

Why don't you try it yourself? In BleachBit you can right-click on any entry to perform a single cleanup. Then you will see that only for the entry [Edge Logs \*] the "\*.log" files in the subfolders of the folder "Local Extension Settings" will be deleted.

I have tested this several times. If you won't believe me, there's nothing more I can do for you.

**Comment by APMichael** [comment] 2020-10-22 12:29
I think we can close this thread. The issue must be fixed by BleachBit. There is nothing else we can do but wait.

**Closed by APMichael** 2020-10-22 12:29 UTC

**Comment by APMichael** [comment] 2021-07-13 16:31
> ... The issue must be fixed by BleachBit. ...

JFYI: The issue is expected to be fixed with the next version (probably version 4.4.1).

https://github.com/bleachbit/bleachbit/pull/1177
